/**
 * src/editor/templates.ts
 *
 * Pre-configured starter templates for creating widgets in WidgeBuddy.
 * Uses DeclarativeWidgetDefinition directly as source of truth.
 *
 * Requirements (Prompt 17):
 * - Initial templates: My Day, Workday, Morning, Evening, Travel, Tasks, Calendar, Weather
 * - Users can: preview, use template, customize, save as their own widget
 * - No separate template rendering system: templates are simply predefined valid WidgetDefinitions.
 */

import { DeclarativeWidgetDefinition } from '@/widgets/declarative/definition';

export interface WidgetTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  definition: DeclarativeWidgetDefinition;
}

export const WIDGET_TEMPLATES: WidgetTemplate[] = [
  // 1. My Day
  {
    id: 'my-day',
    name: 'My Day',
    description: 'Overview of your day with weather, next meeting, and tasks',
    icon: 'sun',
    definition: {
      id: 'my-day-widget',
      displayName: 'My Day',
      description: 'Your complete daily briefing at a glance',
      version: '1.0.0',
      category: 'productivity',
      tags: ['overview', 'daily', 'dashboard'],
      icon: 'sun',
      connectorTypes: ['weather', 'google_calendar', 'todoist'],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-myday-s',
            direction: 'column',
            gap: 6,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'md-greet-s',
                content: 'Good Day ☀️',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'weather',
                id: 'md-weather-s',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: false,
                showWind: false,
                showFeelsLike: false,
                tempUnit: 'auto',
                forecastDays: 1,
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 14,
          root: {
            type: 'container',
            id: 'root-myday-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'container',
                id: 'md-header-row-m',
                direction: 'row',
                gap: 8,
                padding: 0,
                children: [
                  {
                    type: 'text',
                    id: 'md-greeting-m',
                    content: 'Good morning! ☀️',
                    variant: 'title',
                    weight: 'bold',
                    align: 'left',
                  },
                ],
              },
              {
                type: 'weather',
                id: 'md-weather-m',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: true,
                showWind: false,
                showFeelsLike: true,
                tempUnit: 'auto',
                forecastDays: 1,
              },
              {
                type: 'divider',
                id: 'md-div-m',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'event',
                id: 'md-event-m',
                title: 'Team Standup',
                startAt: '2026-10-02T10:00:00.000Z',
                location: 'Google Meet',
                calendarColor: '#6366f1',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-myday-l',
            direction: 'column',
            gap: 10,
            padding: 0,
            children: [
              {
                type: 'container',
                id: 'md-header-l',
                direction: 'column',
                gap: 2,
                padding: 0,
                children: [
                  {
                    type: 'text',
                    id: 'md-title-l',
                    content: 'Good morning, Alex! ☀️',
                    variant: 'heading',
                    weight: 'bold',
                    align: 'left',
                  },
                  {
                    type: 'text',
                    id: 'md-date-l',
                    content: 'Today • 3 tasks remaining',
                    variant: 'caption',
                    weight: 'medium',
                    color: '#64748b',
                    align: 'left',
                  },
                ],
              },
              {
                type: 'weather',
                id: 'md-weather-l',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: true,
                showWind: true,
                showFeelsLike: true,
                tempUnit: 'auto',
                forecastDays: 3,
              },
              {
                type: 'divider',
                id: 'md-div-l1',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'event',
                id: 'md-event-l',
                title: 'Quarterly Planning Sync',
                startAt: '2026-10-02T14:00:00.000Z',
                location: 'Conference Room 4B',
                calendarColor: '#6366f1',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
              {
                type: 'divider',
                id: 'md-div-l2',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'taskList',
                id: 'md-tasks-l',
                maxItems: 3,
                showPriority: true,
                showDueDate: true,
                showProject: true,
                emptyMessage: 'No pending tasks for today',
              },
            ],
          },
        },
      },
    },
  },

  // 2. Workday
  {
    id: 'workday',
    name: 'Workday',
    description: 'Focus during office hours with meeting schedule and priority to-dos',
    icon: 'briefcase',
    definition: {
      id: 'workday-widget',
      displayName: 'Workday',
      description: 'Your productive office cockpit with meetings and priority to-dos',
      version: '1.0.0',
      category: 'productivity',
      tags: ['work', 'tasks', 'calendar', 'focus'],
      icon: 'briefcase',
      connectorTypes: ['google_calendar', 'todoist'],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-work-s',
            direction: 'column',
            gap: 6,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'work-label-s',
                content: 'Workday Focus 💼',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'event',
                id: 'work-event-s',
                title: 'Next: Architecture Review',
                startAt: '2026-10-02T11:00:00.000Z',
                calendarColor: '#0284c7',
                showTime: true,
                showLocation: false,
                isAllDay: false,
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 14,
          root: {
            type: 'container',
            id: 'root-work-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'work-title-m',
                content: 'Workday Priorities',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'event',
                id: 'work-event-m',
                title: 'Design System & Architecture Review',
                startAt: '2026-10-02T11:00:00.000Z',
                location: 'Room 302 / Zoom',
                calendarColor: '#0284c7',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
              {
                type: 'divider',
                id: 'work-div-m',
                orientation: 'horizontal',
                thickness: 1,
                color: '#e2e8f0',
                spacing: 4,
              },
              {
                type: 'taskList',
                id: 'work-tasks-m',
                maxItems: 2,
                showPriority: true,
                showDueDate: true,
                showProject: true,
                emptyMessage: 'All workday tasks complete',
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-work-l',
            direction: 'column',
            gap: 10,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'work-title-l',
                content: 'Workday Command Center',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'event',
                id: 'work-event-l',
                title: 'Design System & Architecture Review',
                startAt: '2026-10-02T11:00:00.000Z',
                location: 'Room 302 / Zoom',
                calendarColor: '#0284c7',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
              {
                type: 'divider',
                id: 'work-div-l',
                orientation: 'horizontal',
                thickness: 1,
                color: '#e2e8f0',
                spacing: 4,
              },
              {
                type: 'taskList',
                id: 'work-tasks-l',
                maxItems: 4,
                showPriority: true,
                showDueDate: true,
                showProject: true,
                emptyMessage: 'All workday tasks complete',
              },
            ],
          },
        },
      },
    },
  },

  // 3. Morning
  {
    id: 'morning',
    name: 'Morning',
    description: 'Start your day with local weather, today’s temperatures, and early appointments',
    icon: 'sunrise',
    definition: {
      id: 'morning-widget',
      displayName: 'Morning Briefing',
      description: 'Start the day informed with weather and your morning schedule',
      version: '1.0.0',
      category: 'lifestyle',
      tags: ['morning', 'weather', 'calendar', 'start'],
      icon: 'sunrise',
      connectorTypes: ['weather', 'google_calendar'],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-morn-s',
            direction: 'column',
            gap: 6,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'morn-greet-s',
                content: 'Good Morning ☀️',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'weather',
                id: 'morn-weather-s',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: false,
                showWind: false,
                showFeelsLike: false,
                tempUnit: 'auto',
                forecastDays: 1,
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 14,
          root: {
            type: 'container',
            id: 'root-morn-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'morn-title-m',
                content: 'Morning Briefing ☕',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'weather',
                id: 'morn-weather-m',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: true,
                showWind: false,
                showFeelsLike: true,
                tempUnit: 'auto',
                forecastDays: 1,
              },
              {
                type: 'divider',
                id: 'morn-div-m',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'event',
                id: 'morn-event-m',
                title: 'First Up: Team Morning Sync',
                startAt: '2026-10-02T09:30:00.000Z',
                location: 'Main Studio',
                calendarColor: '#eab308',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-morn-l',
            direction: 'column',
            gap: 10,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'morn-title-l',
                content: 'Good Morning! 🌅',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'weather',
                id: 'morn-weather-l',
                displayMode: 'detailed',
                showConditionIcon: true,
                showHumidity: true,
                showWind: true,
                showFeelsLike: true,
                tempUnit: 'auto',
                forecastDays: 3,
              },
              {
                type: 'divider',
                id: 'morn-div-l',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'event',
                id: 'morn-event-l',
                title: 'First Up: Team Morning Sync',
                startAt: '2026-10-02T09:30:00.000Z',
                location: 'Main Studio',
                calendarColor: '#eab308',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
            ],
          },
        },
      },
    },
  },

  // 4. Evening
  {
    id: 'evening',
    name: 'Evening',
    description: 'Wind down with completed tasks, tomorrow’s weather, and late headlines',
    icon: 'sunset',
    definition: {
      id: 'evening-widget',
      displayName: 'Evening Wind-Down',
      description: 'Review your day and prepare for tomorrow evening',
      version: '1.0.0',
      category: 'lifestyle',
      tags: ['evening', 'recap', 'news', 'relax'],
      icon: 'sunset',
      connectorTypes: ['todoist', 'weather', 'rss'],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-eve-s',
            direction: 'column',
            gap: 6,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'eve-greet-s',
                content: 'Good Evening 🌙',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'text',
                id: 'eve-sub-s',
                content: 'All tasks reviewed for tomorrow',
                variant: 'caption',
                weight: 'regular',
                color: '#64748b',
                align: 'left',
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 14,
          root: {
            type: 'container',
            id: 'root-eve-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'eve-title-m',
                content: 'Evening Wind-Down 🌙',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'taskList',
                id: 'eve-tasks-m',
                maxItems: 2,
                showPriority: true,
                showDueDate: false,
                showProject: true,
                emptyMessage: 'All clear for tonight!',
              },
              {
                type: 'divider',
                id: 'eve-div-m',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'weather',
                id: 'eve-weather-m',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: true,
                showWind: false,
                showFeelsLike: false,
                tempUnit: 'auto',
                forecastDays: 2,
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-eve-l',
            direction: 'column',
            gap: 10,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'eve-title-l',
                content: 'Evening Review & Wind-down',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'taskList',
                id: 'eve-tasks-l',
                maxItems: 2,
                showPriority: true,
                showDueDate: true,
                showProject: true,
                emptyMessage: 'Day complete!',
              },
              {
                type: 'divider',
                id: 'eve-div-l1',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'weather',
                id: 'eve-weather-l',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: true,
                showWind: true,
                showFeelsLike: true,
                tempUnit: 'auto',
                forecastDays: 2,
              },
              {
                type: 'divider',
                id: 'eve-div-l2',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'articleList',
                id: 'eve-articles-l',
                layout: 'compact',
                maxItems: 2,
                showImage: false,
                showTimestamp: true,
                showSummary: false,
                showAuthor: true,
                emptyMessage: 'No articles',
              },
            ],
          },
        },
      },
    },
  },

  // 5. Travel
  {
    id: 'travel',
    name: 'Travel',
    description: 'On-the-go travel companion with destination weather, itinerary, and checklist',
    icon: 'navigation',
    definition: {
      id: 'travel-widget',
      displayName: 'Travel & Commute',
      description: 'Your trip itinerary, destination forecast, and travel tasks',
      version: '1.0.0',
      category: 'lifestyle',
      tags: ['travel', 'transit', 'weather', 'packing'],
      icon: 'navigation',
      connectorTypes: ['weather', 'google_calendar', 'todoist'],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-trav-s',
            direction: 'column',
            gap: 6,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'trav-label-s',
                content: 'Travel Hub ✈️',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'event',
                id: 'trav-event-s',
                title: 'Flight / Transit Gate',
                startAt: '2026-10-02T16:00:00.000Z',
                calendarColor: '#059669',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 14,
          root: {
            type: 'container',
            id: 'root-trav-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'trav-title-m',
                content: 'Travel Dashboard ✈️',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'event',
                id: 'trav-event-m',
                title: 'Flight UA-402 • Gate B12',
                startAt: '2026-10-02T16:00:00.000Z',
                location: 'Terminal 2',
                calendarColor: '#059669',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
              {
                type: 'divider',
                id: 'trav-div-m',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'weather',
                id: 'trav-weather-m',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: false,
                showWind: false,
                showFeelsLike: true,
                tempUnit: 'auto',
                forecastDays: 1,
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-trav-l',
            direction: 'column',
            gap: 10,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'trav-title-l',
                content: 'Travel Itinerary & Prep',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'event',
                id: 'trav-event-l',
                title: 'Flight UA-402 • Gate B12',
                startAt: '2026-10-02T16:00:00.000Z',
                location: 'Terminal 2',
                calendarColor: '#059669',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
              {
                type: 'divider',
                id: 'trav-div-l1',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'weather',
                id: 'trav-weather-l',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: true,
                showWind: true,
                showFeelsLike: true,
                tempUnit: 'auto',
                forecastDays: 3,
              },
              {
                type: 'divider',
                id: 'trav-div-l2',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'taskList',
                id: 'trav-tasks-l',
                maxItems: 3,
                showPriority: true,
                showDueDate: false,
                showProject: false,
                emptyMessage: 'Packing & boarding pass ready',
              },
            ],
          },
        },
      },
    },
  },

  // 6. Tasks
  {
    id: 'tasks',
    name: 'Tasks',
    description: 'Dedicated to-do manager with interactive checkboxes and priority tags',
    icon: 'check-square',
    definition: {
      id: 'task-widget',
      displayName: 'Task Manager',
      description: 'Keep track of all your active to-dos and deadlines',
      version: '1.0.0',
      category: 'productivity',
      tags: ['tasks', 'todo', 'checklist'],
      icon: 'check-square',
      connectorTypes: ['todoist'],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-task-s',
            direction: 'column',
            gap: 6,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'task-header-s',
                content: 'To-Do List',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'taskList',
                id: 'tasks-list-s',
                maxItems: 2,
                showPriority: false,
                showDueDate: false,
                showProject: false,
                emptyMessage: 'No pending tasks',
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 14,
          root: {
            type: 'container',
            id: 'root-task-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'container',
                id: 'task-header-m',
                direction: 'row',
                gap: 6,
                padding: 0,
                children: [
                  {
                    type: 'icon',
                    id: 'task-icon-m',
                    name: 'check-square',
                    size: 'medium',
                    color: '#6366f1',
                  },
                  {
                    type: 'text',
                    id: 'task-title-m',
                    content: 'My Tasks',
                    variant: 'title',
                    weight: 'bold',
                    align: 'left',
                  },
                ],
              },
              {
                type: 'taskList',
                id: 'tasks-list-m',
                maxItems: 3,
                showPriority: true,
                showDueDate: true,
                showProject: true,
                emptyMessage: 'All tasks completed! 🎉',
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-task-l',
            direction: 'column',
            gap: 10,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'task-title-l',
                content: 'Task Manager',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'taskList',
                id: 'tasks-list-l',
                maxItems: 5,
                showPriority: true,
                showDueDate: true,
                showProject: true,
                emptyMessage: 'All tasks completed! 🎉',
              },
            ],
          },
        },
      },
    },
  },

  // 7. Calendar
  {
    id: 'calendar',
    name: 'Calendar',
    description: 'Upcoming meetings, daily schedule, and appointment locations',
    icon: 'calendar',
    definition: {
      id: 'calendar-widget',
      displayName: 'Calendar Schedule',
      description: 'Your upcoming events, appointments, and meeting schedule',
      version: '1.0.0',
      category: 'calendar',
      tags: ['calendar', 'events', 'schedule', 'meetings'],
      icon: 'calendar',
      connectorTypes: ['google_calendar'],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-cal-s',
            direction: 'column',
            gap: 6,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'cal-label-s',
                content: 'Upcoming Event',
                variant: 'caption',
                weight: 'bold',
                color: '#6366f1',
                align: 'left',
              },
              {
                type: 'event',
                id: 'cal-event-s',
                title: 'Team Standup',
                startAt: '2026-10-02T10:00:00.000Z',
                calendarColor: '#6366f1',
                showTime: true,
                showLocation: false,
                isAllDay: false,
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 14,
          root: {
            type: 'container',
            id: 'root-cal-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'container',
                id: 'cal-header-m',
                direction: 'row',
                gap: 6,
                padding: 0,
                children: [
                  {
                    type: 'icon',
                    id: 'cal-icon-m',
                    name: 'calendar',
                    size: 'medium',
                    color: '#6366f1',
                  },
                  {
                    type: 'text',
                    id: 'cal-title-m',
                    content: 'Today’s Schedule',
                    variant: 'title',
                    weight: 'bold',
                    align: 'left',
                  },
                ],
              },
              {
                type: 'event',
                id: 'cal-event-m1',
                title: 'Sprint Planning Sync',
                startAt: '2026-10-02T10:00:00.000Z',
                location: 'Room 3B / Zoom',
                calendarColor: '#6366f1',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-cal-l',
            direction: 'column',
            gap: 10,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'cal-title-l',
                content: 'Upcoming Schedule',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'event',
                id: 'cal-event-l1',
                title: 'Sprint Planning Sync',
                startAt: '2026-10-02T10:00:00.000Z',
                location: 'Room 3B / Zoom',
                calendarColor: '#6366f1',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
              {
                type: 'divider',
                id: 'cal-div-l1',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'event',
                id: 'cal-event-l2',
                title: 'Design System Polish',
                startAt: '2026-10-02T14:30:00.000Z',
                location: 'Design Studio',
                calendarColor: '#8b5cf6',
                showTime: true,
                showLocation: true,
                isAllDay: false,
              },
            ],
          },
        },
      },
    },
  },

  // 8. Weather
  {
    id: 'weather-focus',
    name: 'Weather',
    description: 'Detailed conditions, temperature, humidity, and multi-day forecast',
    icon: 'cloud-sun',
    definition: {
      id: 'weather-focus-widget',
      displayName: 'Weather Forecast',
      description: 'Live temperature, conditions, and multi-day forecast',
      version: '1.0.0',
      category: 'weather',
      tags: ['weather', 'forecast', 'conditions'],
      icon: 'cloud-sun',
      connectorTypes: ['weather'],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-wf-s',
            direction: 'column',
            gap: 4,
            padding: 0,
            children: [
              {
                type: 'weather',
                id: 'wf-curr-s',
                displayMode: 'compact',
                showConditionIcon: true,
                showHumidity: false,
                showWind: false,
                showFeelsLike: false,
                tempUnit: 'auto',
                forecastDays: 1,
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 14,
          root: {
            type: 'container',
            id: 'root-wf-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'weather',
                id: 'wf-curr-m',
                displayMode: 'detailed',
                showConditionIcon: true,
                showHumidity: true,
                showWind: true,
                showFeelsLike: true,
                tempUnit: 'auto',
                forecastDays: 3,
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-wf-l',
            direction: 'column',
            gap: 10,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'wf-title-l',
                content: 'Weather Forecast',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'weather',
                id: 'wf-curr-l',
                displayMode: 'detailed',
                showConditionIcon: true,
                showHumidity: true,
                showWind: true,
                showFeelsLike: true,
                tempUnit: 'auto',
                forecastDays: 5,
              },
            ],
          },
        },
      },
    },
  },

  // 9. Blank Canvas
  {
    id: 'blank',
    name: 'Blank Canvas',
    description: 'Start fresh with an empty container and your own layout',
    icon: 'layout',
    definition: {
      id: 'custom-widget',
      displayName: 'My Custom Widget',
      description: 'A custom widget crafted with WidgeBuddy',
      version: '1.0.0',
      category: 'productivity',
      tags: ['custom'],
      icon: 'layout',
      connectorTypes: [],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-s',
            direction: 'column',
            gap: 6,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'txt-title-s',
                content: 'My Widget',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'txt-title-m',
                content: 'My Widget',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'text',
                id: 'txt-sub-m',
                content: 'Tap "+ Add Component" to customize your widget.',
                variant: 'caption',
                weight: 'regular',
                color: '#64748b',
                align: 'left',
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-l',
            direction: 'column',
            gap: 12,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'txt-title-l',
                content: 'My Custom Widget',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'text',
                id: 'txt-sub-l',
                content: 'Add components below to build your custom layout.',
                variant: 'body',
                weight: 'regular',
                color: '#64748b',
                align: 'left',
              },
            ],
          },
        },
      },
    },
  },

  // 10. Digital Clock
  {
    id: 'clock',
    name: 'Clock',
    description: 'Minimal local time and date glance banner',
    icon: 'clock',
    definition: {
      id: 'clock-widget',
      displayName: 'Digital Clock',
      description: 'Clean time and date glance widget',
      version: '1.0.0',
      category: 'clock',
      tags: ['clock', 'time', 'date'],
      icon: 'clock',
      connectorTypes: [],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-clock-s',
            direction: 'column',
            gap: 4,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'clock-time-s',
                content: '12:00',
                variant: 'heading',
                weight: 'bold',
                align: 'center',
              },
              {
                type: 'text',
                id: 'clock-date-s',
                content: 'Today',
                variant: 'caption',
                weight: 'medium',
                color: '#64748b',
                align: 'center',
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-clock-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'container',
                id: 'clock-header-m',
                direction: 'row',
                gap: 6,
                padding: 0,
                children: [
                  {
                    type: 'icon',
                    id: 'clock-icon-m',
                    name: 'clock',
                    size: 'small',
                    color: '#0284c7',
                  },
                  {
                    type: 'text',
                    id: 'clock-title-m',
                    content: 'Local Time',
                    variant: 'label',
                    weight: 'semibold',
                    color: '#0284c7',
                    align: 'left',
                  },
                ],
              },
              {
                type: 'text',
                id: 'clock-time-m',
                content: '12:00 PM',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'text',
                id: 'clock-date-m',
                content: 'Friday, October 2',
                variant: 'caption',
                weight: 'medium',
                color: '#64748b',
                align: 'left',
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 18,
          root: {
            type: 'container',
            id: 'root-clock-l',
            direction: 'column',
            gap: 12,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'clock-greet-l',
                content: 'Current Time & Date',
                variant: 'title',
                weight: 'medium',
                color: '#64748b',
                align: 'left',
              },
              {
                type: 'text',
                id: 'clock-time-l',
                content: '12:00:00 PM',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'divider',
                id: 'clock-div-l',
                orientation: 'horizontal',
                thickness: 1,
                color: '#f1f5f9',
                spacing: 4,
              },
              {
                type: 'text',
                id: 'clock-date-l',
                content: 'Friday, October 2 • Local Timezone',
                variant: 'body',
                weight: 'medium',
                align: 'left',
              },
            ],
          },
        },
      },
    },
  },

  // 11. RSS Feed
  {
    id: 'rss-feed',
    name: 'News & RSS',
    description: 'Live articles, headlines, and publication feeds',
    icon: 'rss',
    definition: {
      id: 'rss-widget',
      displayName: 'News & RSS Feed',
      description: 'Live articles and updates from your favorite feeds',
      version: '1.0.0',
      category: 'news',
      tags: ['news', 'rss', 'articles', 'reading'],
      icon: 'rss',
      connectorTypes: ['rss'],
      configFields: [],
      supportedSizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      layouts: {
        small: {
          backgroundColor: '#ffffff',
          padding: 12,
          root: {
            type: 'container',
            id: 'root-rss-s',
            direction: 'column',
            gap: 6,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'rss-label-s',
                content: 'Top Headline 📰',
                variant: 'title',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'articleList',
                id: 'rss-articles-s',
                layout: 'compact',
                maxItems: 1,
                showImage: false,
                showTimestamp: false,
                showSummary: false,
                showAuthor: true,
                emptyMessage: 'No articles',
              },
            ],
          },
        },
        medium: {
          backgroundColor: '#ffffff',
          padding: 14,
          root: {
            type: 'container',
            id: 'root-rss-m',
            direction: 'column',
            gap: 8,
            padding: 0,
            children: [
              {
                type: 'container',
                id: 'rss-header-m',
                direction: 'row',
                gap: 6,
                padding: 0,
                children: [
                  {
                    type: 'icon',
                    id: 'rss-icon-m',
                    name: 'rss',
                    size: 'medium',
                    color: '#ea580c',
                  },
                  {
                    type: 'text',
                    id: 'rss-title-m',
                    content: 'Latest News',
                    variant: 'title',
                    weight: 'bold',
                    align: 'left',
                  },
                ],
              },
              {
                type: 'articleList',
                id: 'rss-articles-m',
                layout: 'compact',
                maxItems: 2,
                showImage: false,
                showTimestamp: true,
                showSummary: false,
                showAuthor: true,
                emptyMessage: 'No articles available',
              },
            ],
          },
        },
        large: {
          backgroundColor: '#ffffff',
          padding: 16,
          root: {
            type: 'container',
            id: 'root-rss-l',
            direction: 'column',
            gap: 10,
            padding: 0,
            children: [
              {
                type: 'text',
                id: 'rss-title-l',
                content: 'Latest Articles & Insights',
                variant: 'heading',
                weight: 'bold',
                align: 'left',
              },
              {
                type: 'articleList',
                id: 'rss-articles-l',
                layout: 'card',
                maxItems: 3,
                showImage: true,
                showTimestamp: true,
                showSummary: true,
                showAuthor: true,
                emptyMessage: 'No articles available',
              },
            ],
          },
        },
      },
    },
  },
];

/**
 * Returns a template by ID or known alias, or the 'blank' template as fallback.
 */
export function getTemplate(templateId?: string): WidgetTemplate {
  if (!templateId) return WIDGET_TEMPLATES[0];

  // Weather aliases
  if (
    templateId === 'weather-card' ||
    templateId === 'weather' ||
    templateId === 'weather-focus'
  ) {
    const weatherTmpl = WIDGET_TEMPLATES.find((t) => t.id === 'weather-focus');
    if (weatherTmpl) return weatherTmpl;
  }

  // Tasks aliases
  if (templateId === 'tasks' || templateId === 'task-list' || templateId === 'task') {
    const tasksTmpl = WIDGET_TEMPLATES.find((t) => t.id === 'tasks');
    if (tasksTmpl) return tasksTmpl;
  }

  // Calendar aliases
  if (templateId === 'calendar' || templateId === 'calendar-list') {
    const calTmpl = WIDGET_TEMPLATES.find((t) => t.id === 'calendar');
    if (calTmpl) return calTmpl;
  }

  // My Day aliases
  if (templateId === 'my-day' || templateId === 'myday') {
    const myDayTmpl = WIDGET_TEMPLATES.find((t) => t.id === 'my-day');
    if (myDayTmpl) return myDayTmpl;
  }

  // Direct ID match
  const found = WIDGET_TEMPLATES.find((t) => t.id === templateId);
  return found ?? WIDGET_TEMPLATES[0];
}
